apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: spring-app
        image: kirankumarhm/camunda-kafka-project:latest
        ports:
        - containerPort: 8090
        env:
        - name: CAMUNDA_BPM_ADMIN_USER
          value: test
          # valueFrom:
          #   secretKeyRef:
          #     name: camunda-secret
          #     key: username
        - name: CAMUNDA_BPM_ADMIN_PASSWORD
          value: test123
          # valueFrom:
          #   secretKeyRef:
          #     name: camunda-secret
          #     key: password

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  type: LoadBalancer
  selector:
    app: spring-app
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
# kubectl apply -f kubernetes.yaml
# minikube service spring-app-service -n force
# minikube service spring-app-service -n force
# minikube ip