server:
  port: 8090

camunda:
  bpm:
    admin-user:
      id: test
      password: test123
    job-execution:
      enabled: true
      deployment-aware: true
    database:
      schema-update: true
      # schema-name: camunda
      # table-prefix: camunda.
      type: postgres
      jdbc-batch-processing: true
      jdbc-batch-processing-size: 10
    history-level: activity
    filter:
      create: All
    metrics:
      enabled: true
    webapp:
      index-redirect-enabled: true
      application-path: /camunda
    generic-properties:
      properties:
        historyTimeToLive: 5
    authorization:
      enabled: true
# spring:
#   datasource:
#     url: "jdbc:h2:file:./camunda-h2-database"
#     username: sa
#     password: ""
#     driver-class-name: org.h2.Driver
#     initialization-mode: always
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         show_sql: true
#         format_sql: true
#         use_sql_comments: true
#         dialect: org.hibernate.dialect.H2Dialect

spring:
  datasource:
    url: "jdbc:postgresql://postgres:5433/camunda"
    username: postgres
    password: "password"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000000
      maximum-pool-size: 10  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      name: myTopic

  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    org.springframework.kafka: DEBUG
